20142314.out:20142314.o linkeddigraph.o util.o
	g++ -o 20142314.out 20142314.o linkeddigraph.o util.o
20142314.o:20142314.cpp
	g++ -c 20142314.cpp
linkeddigraph.o:linkeddigraph.cpp linkeddigraph.h
	g++ -c linkeddigraph.cpp
util.o:util.cpp util.h
	g++ -c util.cpp
clear:
	clear
clean:
	rm *.o 20142314.out