20142314.out:20142314.o maxheap.o util.o
	g++ -o 20142314.out 20142314.o maxheap.o util.o
20142314.o:20142314.cpp
	g++ -c 20142314.cpp
maxheap.o:maxheap.cpp maxheap.h
	g++ -c maxheap.cpp
util.o:util.cpp util.h
	g++ -c util.cpp
clear:
	clear
clean:
	rm *.o 20142314.out