20142314.out:20142314.o linkedlist.o util.o
	g++ -o 20142314.out 20142314.o linkedlist.o util.o
20142314.o:20142314.cpp
	g++ -c 20142314.cpp
linkedlist.o:linkedlist.cpp linkedlist.h
	g++ -c linkedlist.cpp
util.o:util.cpp util.h
	g++ -c util.cpp
clear:
	clear
clean:
	rm *.o 20142314.out