20142314.out:20142314.o stack.o expression.o
	g++ -o 20142314.out 20142314.o stack.o expression.o
20142314.o:20142314.cpp
	g++ -c 20142314.cpp
stack.o:stack.cpp stack.h
	g++ -c stack.cpp
expression.o:expression.cpp expression.h
	g++ -c expression.cpp